### ISSUE TITLE
Xamarin forms map: securityexception-googlecertificatesrslt-not-allowed

### ISSUE THREAD

**Issue by pasha-o** [dmariogatto/Xamarin.Forms.BetterMaps#12]
hi @dmariogatto
there is an issue on new android version, loading the map in xamain forms for android, with the following exception:
`
[MobStoreFlagStore] java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=[], sha256=[c142beced537a77538820983c709acdc4654e0807b6068273c6d9a218d77aaaf], atk=false, ver=231613044.true (go/gsrlt)
[MobStoreFlagStore] 	at ajh.s(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):3)
[MobStoreFlagStore] 	at ajh.get(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):2)
[MobStoreFlagStore] 	at akr.g(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):2)
[MobStoreFlagStore] 	at yp.c(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):1)
[MobStoreFlagStore] 	at yr.run(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):0)
[MobStoreFlagStore] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
[MobStoreFlagStore] 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
[MobStoreFlagStore] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
[MobStoreFlagStore] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
[MobStoreFlagStore] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
[MobStoreFlagStore] 	at java.lang.Thread.run(Thread.java:1012)
[MobStoreFlagStore] Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=[], sha256=[c142beced537a77538820983c709acdc4654e0807b6068273c6d9a218d77aaaf], atk=false, ver=231613044.true (go/gsrlt)
[MobStoreFlagStore] 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
[MobStoreFlagStore] 	at android.os.Parcel.createException(Parcel.java:3007)
[MobStoreFlagStore] 	at android.os.Parcel.readException(Parcel.java:2990)
[MobStoreFlagStore] 	at android.os.Parcel.readException(Parcel.java:2932)
[MobStoreFlagStore] 	at fe.c(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):2)
[MobStoreFlagStore] 	at rs.a(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):4)
[MobStoreFlagStore] 	at jk.e(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):2)
[MobStoreFlagStore] 	at ki.t(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):2)
[MobStoreFlagStore] 	at ki.u(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):3)
[MobStoreFlagStore] 	at ki.e(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):2)
[MobStoreFlagStore] 	at km.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0):74)
[MobStoreFlagStore] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[MobStoreFlagStore] 	at android.os.Looper.loopOnce(Looper.java:226)
[MobStoreFlagStore] 	at android.os.Looper.loop(Looper.java:313)
[MobStoreFlagStore] 	at android.os.HandlerThread.run(HandlerThread.java:67)

`
**It seems the solution is** 
MapsInitializer.initialize(context, **MapsInitializer.Renderer.LATEST**, listener)
Google started to progressively update default render since June 2022 and this maybe could crash using MapsInitializer.Render.LEGACY. 

More on this is [here:](https://developers.google.com/maps/documentation/android-sdk/renderer)

**Comment by dmariogatto** [comment]
I wasn't able to re-create the issue. However, I released a new version that adds a new Android 12 target which allows the renderer to be specified in the `Xamarin.FormsBetterMaps.Init` (it defaults to "LATEST").
